name: Publicar no PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Construir e publicar no PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel

    - name: Construir pacote
      run: python -m build

    - name: Verificar distribuições
      run: twine check dist/*

    - name: Publicar no PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        # Descomente a linha abaixo para publicar no TestPyPI em vez do PyPI
        # repository-url: https://test.pypi.org/legacy/
