name: Testes

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        python-version: [ '3.11' ]

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage-badge
          pip install -e .

      - name: Executar testes com cobertura
        run: |
          pytest tests/ --cov=src/cnpj_cpf_validator --cov-report=xml

      - name: Gerar badge de cobertura
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          coverage-badge -o docs/coverage.svg -f

      - name: Publicar badge no GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
